# Run every 5min and deploy
name: NHSJobsScrape
on:
  schedule:
    - cron: '*/5 * * * *'
jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: pip install -r requirements.txt
    - name: Scrape NHS Jobs
      env:
        GSHEET_ID: ${{ secrets.GSHEET_ID }}
        GOOGLE_APPLICATION_CREDENTIALS: gcreds.json
      run: python main.py
